-- [연습 문제]
-- 회원가입용 테이블 생성(USER_TEST)
-- 컬럼명 : USER_NO(회원번호) - 기본키(PK_USER_TEST), 
--         USER_ID(회원아이디) - 중복금지(UK_USER_ID),
--         USER_PWD(회원비밀번호) - NULL값 허용안함(NN_USER_PWD),
--         PNO(주민등록번호) - 중복금지(UK_PNO), NULL 허용안함(NN_PNO),
--         GENDER(성별) - '남' 혹은 '여'로 입력(CK_GENDER),
--         PHONE(연락처),
--         ADDRESS(주소),
--         STATUS(탈퇴여부) - NOT NULL(NN_STATUS), 'Y' 혹은 'N'으로 입력(CK_STATUS)
-- 각 컬럼의 제약조건에 이름 부여할 것
-- 각 컬럼에 주석 달기
-- 5명 이상 INSERT할 것

CREATE TABLE USER_TEST(
	USER_NO NUMBER CONSTRAINT PK_USER_TEST PRIMARY KEY,
	USER_ID VARCHAR2(20) CONSTRAINT UK_USER_ID UNIQUE,
	USER_PWD VARCHAR2(20) CONSTRAINT NN_USER_PWD NOT NULL,
	PNO CHAR(20) CONSTRAINT UK_PNO UNIQUE CONSTRAINT NN_PNO NOT NULL,
	GENDER CHAR(3) CONSTRAINT CK_GENDER CHECK(GENDER IN('남','여')),
	PHONE CHAR(20),
	ADRESS VARCHAR2(100),
	STATUS CHAR(3) DEFAULT 'N' CONSTRAINT NN_STATUS NOT NULL CONSTRAINT CK_STATUS CHECK(STATUS IN('Y', 'N'))
);

SELECT * FROM USER_TEST;

COMMENT ON COLUMN USER_TEST.USER_NO IS '회원번호';
COMMENT ON COLUMN USER_TEST.USER_ID IS '회원아이디';
COMMENT ON COLUMN USER_TEST.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN USER_TEST.PNO IS '주민등록번호';
COMMENT ON COLUMN USER_TEST.GENDER IS '성별';
COMMENT ON COLUMN USER_TEST.PHONE IS '연락처';
COMMENT ON COLUMN USER_TEST.ADRESS IS '주소';
COMMENT ON COLUMN USER_TEST.STATUS IS '탈퇴여부';

INSERT INTO USER_TEST VALUES('1','user01','pass01','901210-1234564','남','010-1111-1111','서울','N');
INSERT INTO USER_TEST VALUES('2','user02','pass02','861028-2001014','여','010-2222-2222','경기','N');
INSERT INTO USER_TEST VALUES('3','user03','pass03','051024-1111554','남','010-3333-3333','서울','Y');
INSERT INTO USER_TEST VALUES('4','user04','pass04','000505-2233554','여','010-4444-4444','전주','N');
INSERT INTO USER_TEST VALUES('5','user05','pass05','980101-1002525','남','010-5555-5555','서울','N');

-- 테이블 주석 확인
SELECT * FROM USER_COL_COMMENTS
WHERE TABLE_NAME = 'USER_TEST';