/* 연습문제 */
-- 계정 'exam_이니셜' 로 생성 후 해당 계정에서 진행.

/* 테이블명 : MAJOR
 * 1. MAJOR_NO (학과번호) : NUMBER - PK
 * 2. MAJOR_NM (학과명) : VARCHAR2(100) - NOT NULL
 * */

CREATE TABLE MAJOR(
	MAJOR_NO NUMBER CONSTRAINT PK_MAJOR_NO PRIMARY KEY,
	MAJOR_NM VARCHAR2(100) CONSTRAINT NM_MAJOR_NM NOT NULL
);

COMMENT ON COLUMN MAJOR.MAJOR_NO IS '학과번호';
COMMENT ON COLUMN MAJOR.MAJOR_NM IS '학과명';

SELECT * FROM MAJOR;

/* 테이블명 : STUDENT
 * 1. STUDENT_ID (학번) : NUMBER - PK
 * 2. STUDENT_NAME (이름) : VARCHAR2(20) - NOT NULL
 * 3. GENDER (성별) : VARCHAR2(3) CHECK ('남' , '여')
 * 4. BIRTH (생년월일 : 'YYYY-MM-DD '형식으로 작성) : DATE
 * 5. MAJOR_NO (전공학과번호) : NUMBER - FK (부모키 삭제 시 자식키 NULL 로 변경)
 * */

CREATE TABLE STUDENT(
	STUDENT_ID NUMBER CONSTRAINT PK_STUDENT_ID PRIMARY KEY,
	STUDENT_NAME VARCHAR2(20) CONSTRAINT NM_STUDENT_NAME NOT NULL,
	GENDER VARCHAR2(3) CONSTRAINT CK_GENDER CHECK(GENDER IN('남' , '여')),
	BIRTH DATE,
	MAJOR_NO NUMBER CONSTRAINT FK_MAJOR_NO REFERENCES MAJOR ON DELETE SET NULL
);

COMMENT ON COLUMN STUDENT.STUDENT_ID IS '학번';
COMMENT ON COLUMN STUDENT.STUDENT_NAME IS '이름';
COMMENT ON COLUMN STUDENT.GENDER IS '성별';
COMMENT ON COLUMN STUDENT.BIRTH IS '생년월일';
COMMENT ON COLUMN STUDENT.MAJOR_NO IS '전공학과번호';

-- 각 테이블마다 INSERT 5개 이상

-- MAJOR
INSERT INTO MAJOR VALUES(100, '컴퓨터공학과');
INSERT INTO MAJOR VALUES(200, '건축공학과');
INSERT INTO MAJOR VALUES(300, '경영학과');
INSERT INTO MAJOR VALUES(400, '회계학과');
INSERT INTO MAJOR VALUES(500, '의학과');

SELECT * FROM MAJOR;

COMMIT;

-- STUDENT
INSERT INTO STUDENT VALUES(2031019, '홍길동', '남', '2000-10-12',100);
INSERT INTO STUDENT VALUES(1032029, '김말순', '여', '1991-05-05',500);
INSERT INTO STUDENT VALUES(2032222, '김김훈', '남', '1998-01-02',400);
INSERT INTO STUDENT VALUES(2055555, '박나리', '여', '1995-11-11',100);
INSERT INTO STUDENT VALUES(2015155, '김길동', '남', '2000-01-01',300);

SELECT * FROM STUDENT;

COMMIT;

-- MAJOR_NM 학과명 MAJOR_NAME으로 변경해보기

ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME;


